spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
          filters:
            - name: AuthenticationFilter
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
          filters:
            - name: AuthenticationFilter
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/transaction/**
          filters:
            - name: AuthenticationFilter
  application:
    name: API-GATEWAY
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://192.168.2.199:8761/eureka

#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=192.168.2.199
#server.port=8080eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=192.168.2.199
#server.port=8080
#spring.main.web-application-type=NONE
#
#jwt.secret=javasynoverge
#jwt.expirationDateInMs=0
#jwt.refreshExpirationDateInMs=9000000
#
#
## Discover Server Route
#spring.cloud.gateway.routes[0].id=DISCOVERY-SERVER
#spring.cloud.gateway.routes[0].uri=http://eureka:password@${app.eureka-server}:8761
#spring.cloud.gateway.routes[0].predicates[0]=Path=/eureka/web


## Auth Service Route
#spring.cloud.gateway.routes[1].id=AUTH-SERVICE
#spring.cloud.gateway.routes[1].uri=lb://AUTH-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/auth/**
#spring.cloud.gateway.routes[1].predicates[1]=Path=/api/v1/user/**

## Order Service Route
#spring.cloud.gateway.routes[2].id=ORDER-SERVICE
#spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/order/**
#spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter
#
### Product Service Route
#spring.cloud.gateway.routes[3].id=PRODUCT-SERVICE
#spring.cloud.gateway.routes[3].uri=lb://PRODUCT-SERVICE
#spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/product/**
#spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter
#
### Product Service Route
#spring.cloud.gateway.routes[4].id=PAYMENT-SERVICE
#spring.cloud.gateway.routes[4].uri=lb://PAYMENT-SERVICE
#spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/transaction/**
#spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter
